services:
  nextjs-app:
    build: .
    container_name: news-app
    ports:
    # - "HOST_POST:CONTAINER_PORT"
      - "8080:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules  # Prevent overwriting node_modules with host version
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - WATCHPACK_POLLING=true     # Fixes live reload issues
    command: npm run dev  # Ensure the dev server starts properly